# Generated by Django 4.0 on 2022-03-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.CharField(max_length=150)),
                ('Room_no', models.CharField(max_length=5, null=True)),
                ('Beds', models.CharField(max_length=5)),
                ('Rent', models.CharField(max_length=5)),
                ('Floor', models.CharField(max_length=5)),
                ('Image', models.ImageField(null=True, upload_to='room_img')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Dob', models.DateField(null=True)),
                ('Contact', models.CharField(max_length=15)),
                ('Aadhar_no', models.ImageField(upload_to='img/')),
                ('Course', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=15)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
