# Generated by Django 4.0 on 2022-03-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contact_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Dob', models.DateField(null=True)),
                ('Contact', models.CharField(max_length=15)),
                ('Aadhar_pic', models.ImageField(upload_to='img/')),
                ('Profile_pic', models.ImageField(upload_to='img/')),
                ('Course', models.CharField(max_length=20)),
            ],
        ),
    ]
