# Generated by Django 4.0 on 2022-03-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Roll',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='statu',
            field=models.CharField(choices=[('pending', 'pending'), ('allow', 'allow'), ('disallow', 'disallow')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
