# Generated by Django 4.0.2 on 2022-03-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_mess_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('show', 'show'), ('hide', 'hide')], max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='Beds',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='Details',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='Floor',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='Rent',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
