# Generated by Django 4.0 on 2022-03-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_notification_status_alter_room_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
