# Generated by Django 4.0.2 on 2022-03-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_booking_order_id_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Type',
            field=models.CharField(choices=[('pending', 'pending'), ('allow', 'allow'), ('disallow', 'disallow')], max_length=10, null=True),
        ),
    ]
