# Generated by Django 4.0 on 2022-03-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_booking_student_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstudent',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
